# Generated by Django 4.0 on 2024-07-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='image_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
