# Generated by Django 4.0 on 2024-07-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_track_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='added_at',
            field=models.DateTimeField(null=True),
        ),
    ]
