# Generated by Django 4.0 on 2024-07-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_alter_track_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='release_date',
            field=models.DateTimeField(null=True),
        ),
    ]
