# Generated by Django 4.0 on 2024-07-20 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concerts', '0001_initial'),
        ('tracks', '0003_track_added_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=255)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts.concert')),
                ('tracks', models.ManyToManyField(to='tracks.Track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.user')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.user')),
            ],
            options={
                'unique_together': {('user', 'match')},
            },
        ),
    ]
