# Generated by Django 4.0 on 2024-07-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concerts', '0002_market_concert_market_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('markets', models.ManyToManyField(to='concerts.Market')),
            ],
        ),
    ]
