# Generated by Django 4.0 on 2024-07-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField(blank=True, max_length=255)),
                ('image_url', models.URLField(max_length=255)),
                ('attraction_id', models.CharField(max_length=255)),
                ('attraction_name', models.CharField(max_length=255)),
                ('local_date', models.DateField()),
                ('local_time', models.TimeField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=255)),
                ('subgenre', models.CharField(blank=True, max_length=255)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
            options={
                'get_latest_by': 'local_date',
            },
        ),
    ]
