# Generated by Django 4.0 on 2024-07-20 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('market_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='concert',
            name='market_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='concerts.market'),
        ),
    ]
