# Generated by Django 4.0 on 2024-07-20 17:49

from django.db import migrations

def populate_market_data(apps, schema_editor):
    Market = apps.get_model('concerts', 'Market')
    market_data = [
        (1, "Birmingham & More"),
        (2, "Charlotte"),
        (3, "Chicagoland & Northern IL"),
        (4, "Cincinnati & Dayton"),
        (5, "Dallas - Fort Worth & More"),
        (6, "Denver & More"),
        (7, "Detroit, Toledo & More"),
        (8, "El Paso & New Mexico"),
        (9, "Grand Rapids & More"),
        (10, "Greater Atlanta Area"),
        (11, "Greater Boston Area"),
        (12, "Cleveland, Youngstown & More"),
        (13, "Greater Columbus Area"),
        (14, "Greater Las Vegas Area"),
        (15, "Greater Miami Area"),
        (16, "Minneapolis/St. Paul & More"),
        (17, "Greater Orlando Area"),
        (18, "Greater Philadelphia Area"),
        (19, "Greater Pittsburgh Area"),
        (20, "Greater San Diego Area"),
        (21, "Greater Tampa Area"),
        (22, "Houston & More"),
        (23, "Indianapolis & More"),
        (24, "Iowa"),
        (25, "Jacksonville & More"),
        (26, "Kansas City & More"),
        (27, "Greater Los Angeles Area"),
        (28, "Louisville & Lexington"),
        (29, "Memphis, Little Rock & More"),
        (30, "Milwaukee & WI"),
        (31, "Nashville, Knoxville & More"),
        (33, "New England"),
        (34, "New Orleans & More"),
        (35, "New York/Tri-State Area"),
        (36, "Phoenix & Tucson"),
        (37, "Portland & More"),
        (38, "Raleigh & Durham"),
        (39, "Saint Louis & More"),
        (40, "San Antonio & Austin"),
        (41, "N. California/N. Nevada"),
        (42, "Greater Seattle Area"),
        (43, "North & South Dakota"),
        (44, "Upstate New York"),
        (45, "Utah & Montana"),
        (46, "Virginia"),
        (47, "Washington, DC and Maryland"),
        (48, "West Virginia"),
        (49, "Hawaii"),
        (50, "Alaska"),
        (52, "Nebraska"),
        (53, "Springfield"),
        (54, "Central Illinois"),
        (55, "Northern New Jersey"),
        (121, "South Carolina"),
        (122, "South Texas"),
        (123, "Beaumont"),
        (124, "Connecticut"),
        (125, "Oklahoma")
    ]

    for market_id, description in market_data:
        Market.objects.create(market_id=market_id, description=description)

class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_market_concert_market_id'),
    ]

    operations = [
        migrations.RunPython(populate_market_data),
    ]
