# Generated by Django 4.0 on 2024-07-21 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0003_populate_market_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concert',
            old_name='market_id',
            new_name='market',
        ),
    ]
