# Generated by Django 4.0 on 2024-07-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0003_concert_delete_track_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='local_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
