# Generated by Django 4.0 on 2024-07-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0004_rename_market_id_concert_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
